import type { AppNotification, ParkingRequest, Space, Vehicle } from './types';

export const seedVehicles: Vehicle[] = [
  { id: 'v-avante', plate: '12가 3456', name: '현대 아반떼', vClass: 'compact', primary: true },
  { id: 'v-sorento', plate: '34나 9012', name: '기아 쏘렌토', vClass: 'suv', primary: false },
];

export const seedSpaces: Space[] = [
  {
    id: 'seongsu-yard',
    title: '성수 주택 앞 마당',
    area: '성수동2가',
    address: '서울 성동구 성수이로 22길 (승인 후 공개)',
    walk: '성수역 4분',
    price: 2400,
    rating: 4.9,
    reviews: 38,
    responseTime: '평균 3분',
    instant: false,
    maxClass: 'suv',
    dimensions: { width: 2.48, length: 5.32 },
    aiConfidence: 96,
    entryDifficulty: 'easy',
    entryNote: '우측 담장을 따라 천천히 진입하면 됩니다.',
    features: ['독립 공간', '24시간 CCTV', '쉬운 진입'],
    available: '지금부터 4시간',
    availableFromNow: true,
    x: 52,
    y: 47,
    host: { name: '김성호', initial: '김', approvalRate: 98, verified: true },
    ownedByMe: true,
    listed: true,
  },
  {
    id: 'seongsu-villa',
    title: '연무장길 빌라 옆',
    area: '성수동1가',
    address: '서울 성동구 연무장길 (승인 후 공개)',
    walk: '서울숲역 6분',
    price: 2000,
    rating: 4.8,
    reviews: 21,
    responseTime: '평균 5분',
    instant: false,
    maxClass: 'compact',
    dimensions: { width: 2.15, length: 4.7 },
    aiConfidence: 92,
    entryDifficulty: 'normal',
    entryNote: '골목이 좁아 한 번에 진입하는 것을 권장합니다.',
    features: ['골목 진입', '조명 있음', '평지'],
    available: '오늘 19:00까지',
    availableFromNow: true,
    x: 26,
    y: 31,
    host: { name: '이수진', initial: '이', approvalRate: 95, verified: true },
    ownedByMe: false,
    listed: true,
  },
  {
    id: 'ttukseom-store',
    title: '뚝섬 상가 뒤편',
    area: '뚝섬역 인근',
    address: '서울 성동구 아차산로 (승인 후 공개)',
    walk: '뚝섬역 2분',
    price: 3000,
    rating: 5,
    reviews: 14,
    responseTime: '즉시 승인',
    instant: true,
    maxClass: 'largeSuv',
    dimensions: { width: 2.7, length: 5.8 },
    aiConfidence: 98,
    entryDifficulty: 'easy',
    entryNote: '진입로가 넓어 대형 차량도 후진 없이 진입합니다.',
    features: ['넓은 진입로', '야간 조명', '번호판 확인'],
    available: '오늘 23:00까지',
    availableFromNow: true,
    x: 72,
    y: 24,
    host: { name: '박정우', initial: '박', approvalRate: 100, verified: true },
    ownedByMe: false,
    listed: true,
  },
  {
    id: 'seoulforest-house',
    title: '서울숲 단독주택 담장 옆',
    area: '서울숲길',
    address: '서울 성동구 서울숲길 (승인 후 공개)',
    walk: '서울숲 3분',
    price: 2800,
    rating: 4.7,
    reviews: 9,
    responseTime: '평균 8분',
    instant: false,
    maxClass: 'sedan',
    dimensions: { width: 2.3, length: 5.0 },
    aiConfidence: 90,
    entryDifficulty: 'normal',
    entryNote: '담장 모서리에서 핸들을 크게 돌려야 합니다.',
    features: ['주택가', '조용한 공간', '평지'],
    available: '18:00부터',
    availableFromNow: false,
    x: 35,
    y: 67,
    host: { name: '최민경', initial: '최', approvalRate: 93, verified: true },
    ownedByMe: false,
    listed: true,
  },
  {
    id: 'wangsimni-tower',
    title: '왕십리역 오피스텔 지하',
    area: '행당동',
    address: '서울 성동구 왕십리로 (승인 후 공개)',
    walk: '왕십리역 3분',
    price: 3500,
    rating: 4.6,
    reviews: 27,
    responseTime: '즉시 승인',
    instant: true,
    maxClass: 'suv',
    dimensions: { width: 2.4, length: 5.2 },
    aiConfidence: 94,
    entryDifficulty: 'normal',
    entryNote: '지하 1층 램프 경사가 있어 저속 진입하세요.',
    features: ['실내 주차', '전기차 충전', '보안 게이트'],
    available: '지금부터 6시간',
    availableFromNow: true,
    x: 60,
    y: 62,
    host: { name: '정하늘', initial: '정', approvalRate: 97, verified: true },
    ownedByMe: false,
    listed: true,
  },
  {
    id: 'majang-market',
    title: '마장동 축산시장 옆 공터',
    area: '마장동',
    address: '서울 성동구 마장로 (승인 후 공개)',
    walk: '마장역 5분',
    price: 1800,
    rating: 4.4,
    reviews: 6,
    responseTime: '평균 12분',
    instant: false,
    maxClass: 'largeSuv',
    dimensions: { width: 2.9, length: 6.0 },
    aiConfidence: 88,
    entryDifficulty: 'easy',
    entryNote: '평지 공터라 진입이 자유롭습니다.',
    features: ['넓은 공간', '대형 가능', '주말 여유'],
    available: '오늘 21:00까지',
    availableFromNow: true,
    x: 82,
    y: 48,
    host: { name: '한도경', initial: '한', approvalRate: 90, verified: false },
    ownedByMe: false,
    listed: true,
  },
  {
    id: 'oksu-hill',
    title: '옥수동 언덕집 주차칸',
    area: '옥수동',
    address: '서울 성동구 독서당로 (승인 후 공개)',
    walk: '옥수역 7분',
    price: 2200,
    rating: 4.9,
    reviews: 18,
    responseTime: '평균 4분',
    instant: false,
    maxClass: 'sedan',
    dimensions: { width: 2.28, length: 4.95 },
    aiConfidence: 91,
    entryDifficulty: 'tricky',
    entryNote: '경사로에서 후진 진입해야 하며 초보에게는 어렵습니다.',
    features: ['한강 조망', '조용한 골목', '경사 주의'],
    available: '지금부터 3시간',
    availableFromNow: true,
    x: 18,
    y: 74,
    host: { name: '서지안', initial: '서', approvalRate: 96, verified: true },
    ownedByMe: false,
    listed: true,
  },
  {
    id: 'seongsu-cafe',
    title: '카페거리 안쪽 전용칸',
    area: '성수동2가',
    address: '서울 성동구 서울숲2길 (승인 후 공개)',
    walk: '성수역 6분',
    price: 3200,
    rating: 4.8,
    reviews: 31,
    responseTime: '즉시 승인',
    instant: true,
    maxClass: 'suv',
    dimensions: { width: 2.5, length: 5.35 },
    aiConfidence: 95,
    entryDifficulty: 'easy',
    entryNote: '카페 건물 옆 전용칸으로 바로 진입합니다.',
    features: ['카페거리', '즉시 승인', '넓은 폭'],
    available: '오늘 22:00까지',
    availableFromNow: true,
    x: 44,
    y: 18,
    host: { name: '문가람', initial: '문', approvalRate: 99, verified: true },
    ownedByMe: false,
    listed: true,
  },
];

const now = Date.now();

export const seedRequests: ParkingRequest[] = [
  {
    id: 'req-incoming-1',
    side: 'received',
    spaceId: 'seongsu-yard',
    spaceTitle: '성수 주택 앞 마당',
    createdAt: now - 8 * 60_000,
    startLabel: '오늘 오후 8:00',
    durationHours: 2,
    price: 4800,
    vehiclePlate: '34나 9012',
    vehicleName: '기아 셀토스',
    fitScore: 94,
    status: 'pending',
    guest: { name: '민지', initial: '민', rating: 4.9, trips: 12, reports: 0 },
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: 'noti-seed-1',
    kind: 'request',
    title: '새 이용 요청',
    body: '민지님이 성수 주택 앞 마당을 오늘 20:00부터 2시간 이용 요청했어요.',
    createdAt: now - 8 * 60_000,
    read: false,
  },
  {
    id: 'noti-seed-2',
    kind: 'system',
    title: '주차모아를 시작했어요',
    body: 'AI 공간 검증과 호스트 사전승인으로 안심 주차를 시작하세요.',
    createdAt: now - 26 * 60 * 60_000,
    read: true,
  },
];
