import type { Space } from './types';

export const spaces: Space[] = [
  {
    id: 'seongsu-yard',
    title: '성수 주택 앞 마당',
    area: '성수동2가',
    walk: '성수역 도보 4분',
    price: 2400,
    rating: 4.9,
    reviews: 38,
    fitScore: 96,
    responseTime: '평균 3분',
    vehicle: 'SUV까지',
    features: ['독립 공간', '24시간 CCTV', '쉬운 진입'],
    available: '지금부터 4시간',
    x: 52,
    y: 47,
  },
  {
    id: 'seongsu-villa',
    title: '연무장길 빌라 옆',
    area: '성수동1가',
    walk: '서울숲역 도보 6분',
    price: 2000,
    rating: 4.8,
    reviews: 21,
    fitScore: 92,
    responseTime: '평균 5분',
    vehicle: '준중형까지',
    features: ['골목 진입', '조명 있음', '평지'],
    available: '19:00까지',
    x: 26,
    y: 31,
  },
  {
    id: 'tukseom-store',
    title: '뚝섬 상가 뒤편',
    area: '뚝섬역 인근',
    walk: '뚝섬역 도보 2분',
    price: 3000,
    rating: 5,
    reviews: 14,
    fitScore: 98,
    responseTime: '즉시 승인',
    vehicle: '대형 SUV까지',
    features: ['넓은 진입로', '야간 조명', '번호판 확인'],
    available: '오늘 23:00까지',
    x: 72,
    y: 24,
  },
  {
    id: 'seoulforest-house',
    title: '서울숲 단독주택 담장 옆',
    area: '서울숲길',
    walk: '서울숲 도보 3분',
    price: 2800,
    rating: 4.7,
    reviews: 9,
    fitScore: 90,
    responseTime: '평균 8분',
    vehicle: '중형 세단까지',
    features: ['주택가', '조용한 공간', '평지'],
    available: '18:00부터',
    x: 35,
    y: 67,
  },
];

export const formatWon = (value: number) => `${value.toLocaleString('ko-KR')}원`;
